ordering:
  m-login:
    m-ingreso: ''
    m-editar-datos: ''
    m-cerrar-sesion: ''
  __particle-sMLvt: ''
items:
  m-login:
    id: 128
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
    icon: 'fa fa-user-circle fa-lg'
    columns:
      - 100
  m-login/m-ingreso:
    id: 125
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
    icon: 'fa fa-lock'
  m-login/m-editar-datos:
    id: 126
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
    icon: 'fa fa-user-md'
  m-login/m-cerrar-sesion:
    id: 127
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
    icon: 'fa fa-unlock'
  __particle-sMLvt:
    type: particle
    particle: custom
    title: 'Custom HTML'
    options:
      particle:
        enabled: '1'
        html: "<?php\n$usuario =JFactory::getUser()->get('name');\nif ($usuario<>''){\necho $usuario;\n}\n?>"
        twig: '1'
        filter: '1'
      block:
        extra: {  }
    enabled: '1'
